export enum Rol {
  ADMIN = 'ADMIN',
  ASISTENTE = 'ASISTENTE',
  MECANICO = 'MECANICO',
}

export enum Modules {
  CLIENT = 'CLIENT',
  VEHICLE = 'VEHICLE',
  FACTURA = 'FACTURA',
  USUARIO = 'USUARIO',
}

export enum EstadoReparacion {
  REGISTRADO = 'REGISTRADO',
  EN_DIAGNOSTICO = 'EN DIAGNOSTICO',
  EN_REPARACION = 'EN REPARACION',
  EN_MANTENIMIENTO = 'EN MANTENIMIENTO',
  EN_ESPERA = 'EN ESPERA',
  REPARADO = 'REPARADO',
  NO_REPARABLE = 'NO REPARABLE',
  ENTREGADO = 'ENTREGADO',
}

